# Generated by Django 5.0.3 on 2024-04-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceapplication',
            name='platform',
            field=models.CharField(blank=True, choices=[('Trendyol', 'Trendyol'), ('Hepsiburada', 'Hepsiburada'), ('Amazon', 'Amazon')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceapplication',
            name='store_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
